# Generated by Django 3.1.2 on 2022-08-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippet', '0003_products_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['created'], 'permissions': (('manager_permission', 'Manager Permission'),)},
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippet.sales')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
